import ExistentialRules.ChaseSequence.Termination.BacktrackingOfFacts.Basic
import ExistentialRules.ChaseSequence.Termination.BacktrackingOfFacts.PreGroundTerm
import ExistentialRules.ChaseSequence.Termination.BacktrackingOfFacts.GroundTerm
import ExistentialRules.ChaseSequence.Termination.BacktrackingOfFacts.PreTrigger
import ExistentialRules.ChaseSequence.Termination.BacktrackingOfFacts.ChaseBranch

