module

public import ExistentialRules.ChaseSequence.Termination.BacktrackingOfFacts.Basic
public import ExistentialRules.ChaseSequence.Termination.BacktrackingOfFacts.PreGroundTerm
public import ExistentialRules.ChaseSequence.Termination.BacktrackingOfFacts.GroundTerm
public import ExistentialRules.ChaseSequence.Termination.BacktrackingOfFacts.PreTrigger
public import ExistentialRules.ChaseSequence.Termination.BacktrackingOfFacts.ChaseBranch

