import ExistentialRules.ChaseSequence.Termination.RenameConstantsApart.PreGroundTerm
import ExistentialRules.ChaseSequence.Termination.RenameConstantsApart.GroundTerm
import ExistentialRules.ChaseSequence.Termination.RenameConstantsApart.PreTrigger

